[features]
seeds = false
skip-lint = false
[programs.localnet]
crunchy_vs_smooth = "99xsRxMDZJFTXr3S8Xu3eU8afc4kYeawscL2NC8PcqTL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/nawed2611/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
